#+TITLE: IDE
#+AUTHOR: Emmanuel Agullo and Mathieu Faverge
#+SETUPFILE: ../include/compose-publish/theme-readtheorginria.setup
#+PROPERTY: header-args:bash :eval no :exports both

* Back-end: building compile-commands.json

In the same proper software environment as above (with either [[./setup-guix.org][guix]] or
[[./setup-plafrim.org][environment modules]]), you can alternatively build the project with the
[[https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html][-DCMAKE_EXPORT_COMPILE_COMMANDS=ON]] =cmake= option, e.g.:

   #+begin_src bash :eval no
     cd ./mini-chameleon
     mkdir -p build/debug/
     cmake -B build/debug/ -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -DENABLE_MPI=ON -DENABLE_STARPU=ON .
     ln -s build/debug/compile_commands.json .
   #+end_src

   It is also possible -- but not necessary if the objective is only to obtain
   the ~compile_commands.json~ database -- to build the project with that set
   up: ~cmake --build build/debug~.

* Front-end: emacs-bedrock

A possible minimal IDE can be:

#+begin_src bash
  guix shell --pure emacs-bedrock-as-default -D mini-chameleon clang-toolchain -- emacs -nw
#+end_src

Note that we use ~emacs -nw~ on plafrim to have a no (X) window, which
would otherwise be to slow on =plafrim=. In this context, the top menu
can be accessed with =F10=. You can for instan press =F10= and =Enter=
to visit a new file.

When editing a source code file (such as a ~.c~ file), you can turn on
auto-completion once again by pressing =F10= to access the menu, then
=Tools= and then =Language Server Support (Eglot)=.

Note that the [[https://www.gnu.org/software/emacs/manual/html_node/emacs/CUA-Bindings.html][usual Windows-like]] cut (~C-x~), copy (~C-c~), and paste
(~C-v~) can be used.

# Of course, the standard ~emacs~ key bindings are also available. If
# you prefer ~vim~-like key bindings ...

* COMMENT Front-end: minimal emacs with lsp on plafrim

We follow: https://emacs-lsp.github.io/lsp-mode/tutorials/CPP-guide/, which we adapt with =guix=.

We install emacs and required packages:
#+begin_src bash
guix install emacs emacs-lsp-mode emacs-yasnippet emacs-lsp-treemacs emacs-helm-lsp emacs-projectile emacs-hydra emacs-flycheck emacs-company emacs-avy emacs-which-key emacs-helm-xref emacs-dap-mode ccls emacs-ccls
#+end_src

Here is a minimalist ~~/.bash_profile~:
#+begin_src bash
export GUIX_LOCPATH=$HOME/.guix-profile/lib/locale

GUIX_PROFILE="$HOME/.config/guix/current"
. "$GUIX_PROFILE/etc/profile"

GUIX_PROFILE="$HOME/.guix-profile"
. "$GUIX_PROFILE/etc/profile"
#+end_src

And here is an example of a minimalist initialization file
(~~/.emacs.d/init.el~):

#+begin_src bash
;; sample `helm' configuration use https://github.com/emacs-helm/helm/ for details
(helm-mode)
(require 'helm-xref)
(define-key global-map [remap find-file] #'helm-find-files)
(define-key global-map [remap execute-extended-command] #'helm-M-x)
(define-key global-map [remap switch-to-buffer] #'helm-mini)

(which-key-mode)
(add-hook 'c-mode-hook 'lsp)
(add-hook 'c++-mode-hook 'lsp)

(setq gc-cons-threshold (* 100 1024 1024)
      read-process-output-max (* 1024 1024)
      treemacs-space-between-root-nodes nil
      company-idle-delay 0.0
      company-minimum-prefix-length 1
      lsp-idle-delay 0.1)  ;; clangd is fast

(with-eval-after-load 'lsp-mode
  (add-hook 'lsp-mode-hook #'lsp-enable-which-key-integration)
  (require 'dap-cpptools)
  (yas-global-mode)
  (define-key lsp-mode-map (kbd "C-c l") lsp-command-map))
#+end_src

Note that we define the leader key for =lsp-mode= in the ultimate line:
~(define-key lsp-mode-map (kbd "C-c l") lsp-command-map)~. In this case, it is
~C-c l~ (~CTRL-c l~) but feel free to choose the one you like.
