#+TITLE: Getting started
#+AUTHOR: Emmanuel Agullo and Mathieu Faverge
#+SETUPFILE: ../include/compose-publish/theme-readtheorginria.setup
#+PROPERTY: header-args:bash :eval no :exports both

* Resources

label:ressources

** This project

You can [[https://solverstack.gitlabpages.inria.fr/mini-examples/mini-chameleon/][browse]] or visit the [[https://gitlab.inria.fr/solverstack/mini-examples/mini-chameleon/][source]] of the project.

Note: This project was initiated in the context of the IS321 of the
=enseirb-matmeca= =cisd= option, for which we provide an [[./setup-cisd.org][extra collaborative set
up]].

** Code

The reference code is available in the [[https://gitlab.inria.fr/solverstack/mini-examples/mini-chameleon/][source]] of this project:
[[https://gitlab.inria.fr/solverstack/mini-examples/mini-chameleon/]]. It may be
cloned and forked. The clone set up must be performed with the
~--recurse-submodules~ option. The clone may be performed either via ~https~ or
~ssh~.

- clone via ~https~:

#+begin_src bash
git clone --recurse-submodules https://gitlab.inria.fr/solverstack/mini-examples/mini-chameleon.git
#+end_src

- clone via ~ssh~:

#+begin_src bash
git clone --recurse-submodules git@gitlab.inria.fr:solverstack/mini-examples/mini-chameleon.git
#+end_src

Other options are possible, such as cloning from a fork, as in the case of [[./setup-cisd.org][cisd
option at enseirb-matmeca]].

* Hardware environment

The project is not entitled with any particular hardware environment but we
provide [[./setup-plafrim.org][here]] specific instructions for the [[https://www.plafrim.fr][plafrim]] machine.

* Software environment
  :PROPERTIES:
  :ID:       a824dae5-55ca-4a27-a17a-32b11b48ec55
  :END:

label:env

The project comes with advanced [[../cmake_modules][CMake modules]] to ensure the proper detection of
the software dependencies. We however provide [[./setup-guix.org][here]] specific instructions for the
=guix= environment. They can be used on any machine onto which =guix= is
available, including =plafrim=. We also propose =environment modules= in the
case in the [[./setup-plafrim.org][plafrim]] case. In a nutshell, proceed with
- either [[./setup-guix.org][guix set up]] (on any machine having =guix= installed, including
  =plafrim=);
- or [[./setup-plafrim.org][plafrim modules]] (on =plafrim= only).

* Mise en place

** Gestion des ressources avec =slurm= (mono-noeud)

   Voici un petit rappel de quelques commandes =slurm= utiles pour gérer les
   ressources =plafrim-formation= auxquelles vous voulez accéder :

   #+begin_src bash :eval no
     sinfo
     salloc -p <partition> -N <number of nodes>
     ssh <node id>
     sbatch <batch script>
     squeue -u <login name>
     scontrol show jobid <job id>
     scancel <job id>
   #+end_src

   Dans ce TP, nous n'utiliserons qu'un seul noeud homogène, de type ~miriel~:

   #+begin_src
   salloc -p miriel -N 1
   ssh <node id>
   #+end_src

   Tant qu'il s'agit de développer le code, pour ne pas trop saturer
   l'utilisation des ressources, merci de ne pas utiliser l'option
   ~--exclusive~, et de garder celle-ci pour vos réservations dédiées à des
   études de performance (pour lesquelles vous préférerez sans doute utiliser
   ~sbatch~).

   Merci d'effectuer l'ensemble de votre travail (édition, compilation, tests)
   depuis un noeud de calcul pour éviter de surcharger la frontale.

** Construction de la bibliothèque et des testeurs

Once the proper software environment has been set up (with either [[./setup-guix.org][guix]] or
[[./setup-plafrim.org][environment modules]]), you can build the project:

   #+begin_src bash :eval no
     cd ./mini-chameleon
     mkdir -p build/default
     cmake -B build/default -DENABLE_MPI=ON -DENABLE_STARPU=ON .
     cmake --build build/default
   #+end_src

   Les options =cmake= ~-DENABLE_MPI=ON -DENABLE_STARPU=ON~ sont facultatives
   pour le moment et peuvent être ignorés tant que l'on reste en séquentiel ou
   multi-threadé.

** How about auto-completion?

*** Back-end: building compile-commands.json

In the same proper software environment as above (with either [[./setup-guix.org][guix]] or
[[./setup-plafrim.org][environment modules]]), you can alternatively build the project with the
[[https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html][-DCMAKE_EXPORT_COMPILE_COMMANDS=ON]] =cmake= option, e.g.:

   #+begin_src bash :eval no
     cd ./mini-chameleon
     mkdir -p build/debug/
     cmake -B build/debug/ -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -DENABLE_MPI=ON -DENABLE_STARPU=ON .
     ln -s build/debug/compile_commands.json .
   #+end_src

   It is also possible -- but not necessary if the objective is only to obtain
   the ~compile_commands.json~ database -- to build the project with that set
   up: ~cmake --build build/debug~.

*** Front-end: minimal emacs with lsp on plafrim

We follow: https://emacs-lsp.github.io/lsp-mode/tutorials/CPP-guide/, which we adapt with =guix=.

We install emacs and required packages:
#+begin_src bash
guix install emacs emacs-lsp-mode emacs-yasnippet emacs-lsp-treemacs emacs-helm-lsp emacs-projectile emacs-hydra emacs-flycheck emacs-company emacs-avy emacs-which-key emacs-helm-xref emacs-dap-mode ccls emacs-ccls
#+end_src

Here is a minimalist ~~/.bash_profile~:
#+begin_src bash
export GUIX_LOCPATH=$HOME/.guix-profile/lib/locale

GUIX_PROFILE="$HOME/.config/guix/current"
. "$GUIX_PROFILE/etc/profile"

GUIX_PROFILE="$HOME/.guix-profile"
. "$GUIX_PROFILE/etc/profile"
#+end_src

And here is an example of a minimalist initialization file
(~~/.emacs.d/init.el~):

#+begin_src bash
;; sample `helm' configuration use https://github.com/emacs-helm/helm/ for details
(helm-mode)
(require 'helm-xref)
(define-key global-map [remap find-file] #'helm-find-files)
(define-key global-map [remap execute-extended-command] #'helm-M-x)
(define-key global-map [remap switch-to-buffer] #'helm-mini)

(which-key-mode)
(add-hook 'c-mode-hook 'lsp)
(add-hook 'c++-mode-hook 'lsp)

(setq gc-cons-threshold (* 100 1024 1024)
      read-process-output-max (* 1024 1024)
      treemacs-space-between-root-nodes nil
      company-idle-delay 0.0
      company-minimum-prefix-length 1
      lsp-idle-delay 0.1)  ;; clangd is fast

(with-eval-after-load 'lsp-mode
  (add-hook 'lsp-mode-hook #'lsp-enable-which-key-integration)
  (require 'dap-cpptools)
  (yas-global-mode))

(define-key lsp-mode-map (kbd "C-c l") lsp-command-map)
#+end_src

Note that we define the leader key for =lsp-mode= in the ultimate line:
~(define-key lsp-mode-map (kbd "C-c l") lsp-command-map)~. In this case, it is
~C-c l~ (~CTRL-c l~) but feel free to choose the one you like.
