#+TITLE: Getting started
#+SUBTITLE: Plafrim
#+AUTHOR: Emmanuel Agullo and Mathieu Faverge
#+SETUPFILE: ../include/compose-publish/theme-readtheorginria.setup
#+PROPERTY: header-args:bash :eval no :exports both

* Connexion à plafrim-formation

Nous allons travailler sur [[https://www.plafrim.fr][plafrim]] par [[https://fr.wikipedia.org/wiki/Secure_Shell][ssh]]. Vous avez reçu les instructions pour
vous connecter à la machine par mail. En supposant que ~<myname>~ est votre nom,
voici comment vous connecter:

#+begin_src bash :eval no :results output :exports both
ssh <myname>@formation.plafrim.fr
ssh plafrim
#+end_src

Après ces deux étapes, vous devriez être sur ~miriel045~, ce que vous pouvez
vérifier:
#+begin_src bash :results output :exports both
hostname
#+end_src

Ces deux étapes peuvent être effectués d'une seule traite en ajoutant les lignes
suivantes dans votre ~.ssh/config~, où ~<myname>~ est à nouveau à changer:

#+begin_src bash :results output :exports both
Host plafrim-formation
        ForwardAgent yes
        ForwardX11 yes
        User <myname>
        ProxyCommand ssh -T -q -o "ForwardAgent yes" -l <myname> formation.plafrim.fr 'ssh-add -t 1 && nc plafrim 22'
#+end_src

Pour vous connecter, il vous suffit ensuite d'effectuer:
#+begin_src bash :results output :exports both
ssh -X plafrim-formation
#+end_src

* Software dependencies

The software environment may be handled via either [[https://modules.readthedocs.io/en/latest/][environment modules]] or [[https://guix.gnu.org/][guix]].

** Via =environment module=

A first option is to use [[https://modules.readthedocs.io/en/latest/][environment modules]]. The required modules are available
in [[../plafrim-formation-env.sh]], which may be sourced. Assuming to be at the root
of a clone of the project:

   #+begin_src bash
   source ./plafrim-formation-env.sh
   #+end_src

** Via =guix=

Because [[https://guix.gnu.org/][guix]] is available on =plafrim=, the [[./setup-cisd.org][guix setup]] can also be used. An
advantage over the [[https://modules.readthedocs.io/en/latest/][environment modules]] is that this method allows one to fully
control the environment without requiring any particular library to be
pre-installed. It is also cross-platform. For instance, the same set up can be
employed on your laptop and on =plafrim=.

If you choose this method, please proceed with the [[./setup-guix.org][guix setup]].

** COMMENT Via modules generated through =guix=

There is a third option: using modules generated through =guix=.

#+begin_src bash
module load bash-minimal/5.1.8 binutils/2.37 bzip2/1.0.8 cmake-minimal/3.21.4 coreutils/8.32 diffutils/3.8 file/5.39 findutils/4.8.0 gawk/5.1.0 gcc/10.3.0 gfortran/10.3.0 glibc/2.33 glibc-static/2.33 glibc-utf8-locales/2.33 grep/3.6 gzip/1.10 hwloc-lib/2.8.0 ld-wrapper/0 libpciaccess/0.16 linux-libre-headers/5.10.35 make/4.3 openblas/0.3.20 openmpi/4.1.4 openssh/8.9p1 patch/2.7.6 pkg-config/0.29.2 python/3.9.9 sed/4.8 starpu/1.3.9 tar/1.34 xz/5.2.5
#+end_src
