#+TITLE: The =mini-chameleon= educational-purpose project
#+AUTHOR: Emmanuel Agullo and Mathieu Faverge
#+SETUPFILE: ./include/compose-publish/theme-readtheorginria.setup

* =mini-chameleon=

=mini-chameleon= is an *educational-purpose* project aiming at designing a dense
linear algebra solver. At the beginning, the project comes only with testing
routines while the actual computational routines remain to be completed. The
goal is to implement a dense matrix-matrix product (GEMM) and an LU
factorization (GETRF). The project is named after the fully-featured [[https://gitlab.inria.fr/solverstack/chameleon][chameleon]]
dense linear algebra library.

The first step of the project consists in implementing a =sequential= version of
the routines, including blocking strategies and vectorization. The second step
is a shared-memory (=openmp=) implementation. The third step is a distributed
memory (=mpi=) version. The fourth step is an hybrid =mpi+openmp= version. There
is also the possibility to implement a runtime-based (=starpu=) version.

* Objectives

The main objectives of this project is to develop by yourself a small
linear algebra library (that includes a GEMM, and a GETRF without
piviting) with the highest possible performance for:

- the sequential kernels
- the multi-threaded kernels
- the MPI only implementation
- and as a bonus, the MPI+thread implemtation.

All developments will need to be carefully studied and explained in
your report for each of these versions. Comparative studies of the
results using R figures will be asked to show the good performances,
and the improvement brought by each proposed functionnality.

As a complement to the report, a presentation of the results will be
made. This presentation will be taken into account for the evaluation
of the English class.

* Browse this page

You can [[https://solverstack.gitlabpages.inria.fr/mini-examples/mini-chameleon/][browse]] or visit the [[https://gitlab.inria.fr/solverstack/mini-examples/mini-chameleon/][source]] of this page.

* Getting started

- [[./tutorial/setup.org][Get started!]]
- [[./tutorial/tuto-chameleon.org][Tutorial]]: from basic /hello world/ to =slurm=, =mpi= and =guix=.

* Steps

- [[./tutorial/step1-sequential.org][step 1: sequential design]]
- [[./tutorial/step2-omp.org][step 2: shared-memory design (=openmp=)]]
- [[./tutorial/step3-mpi.org][step 3: distributed-memory design (=mpi=)]]
