#+TITLE: The =mini-chameleon= educational-purpose project
#+AUTHOR: Emmanuel Agullo and Mathieu Faverge
#+SETUPFILE: ./include/compose-publish/theme-readtheorginria.setup

* The =mini-chameleon= educational-purpose project

=mini-chameleon= is an *educational-purpose* project aiming at designing a dense
linear algebra solver. At the beginning, the project comes only with testing
routines while the actual computational routines remain to be completed. The
goal is to implement a dense matrix-matrix product (GEMM) and an LU
factorization (GETRF).

The first step consists in a basic =sequential= implementation, possibly
considering blocking strategies. The second step is a =simd= enhancement. The
third step is a shared-memory (=openmp=) implementation. The fourth step is a
distributed memory (=mpi=) version. The fifth step is an hybrid =mpi+openmp=
version. There is also the possibility to implement a runtime-based (=starpu=)
version.

The project is named after the fully-featured [[https://gitlab.inria.fr/solverstack/chameleon][chameleon]] dense linear algebra
library.

* Browse this page

You can [[https://solverstack.gitlabpages.inria.fr/mini-examples/mini-chameleon/][browse]] or visit the [[https://gitlab.inria.fr/solverstack/mini-examples/mini-chameleon/][source]] of this page.

* COMMENT Getting started

[[https://link.infini.fr/cisd-2022]]
